apiVersion: v1
kind: Service 
metadata:
  name: kkapp1-headless-service
spec:
  clusterIP: None
  selector:
    app: kkapp1
  ports: 
    - name: http
      port: 8080 # Service Port
      targetPort: 8080 # Container Port