name: PR Data Collector

on:
  pull_request:
    types:
      - closed
      - opened
    branches:
      - main
      - master
  pull_request_target:
    types:
      - opened
    branches:
      - main
      - master

jobs:
  collect_and_send_pr_data:
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.merged == true) ||
      (startsWith(github.event.pull_request.title, 'Revert:'))
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Collect and send PR data
        env:
          GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_PR_LINK: ${{ github.event.pull_request.html_url }}
          GITHUB_PR_MERGED_AT: ${{ github.event.pull_request.merged_at }}
          GITHUB_PR_COMMIT_HASH: ${{ github.event.pull_request.merge_commit_sha }}
          GITHUB_PR_DESCRIPTION: ${{ github.event.pull_request.body }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python .github/scripts/collect_and_store_pr_data.py
